version: '3'

services:
  postgres:
    image: postgres
    container_name: database_pg
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    logging:
      driver: none
    ports:
      - 5432:5432
    volumes:
      - .:/usr/db/pg

  mongo:
    image: mongo
    restart: always
    container_name: database_mongo
    logging:
      driver: none
    ports:
      - 27017:27017
    volumes:
      - .:/usr/db/pg

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - .:/usr/db/redis

  mysql:
    image: mysql
    platform: linux/amd64
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - .:/usr/db/mysql
    ports:
      - 3306:3306